### ISSUE TITLE
Second "/loop/#/hit record " not working propertly

### ISSUE THREAD

**Issue by ToFFmashines** [jean-emmanuel/loop192#3]
Hi,
I'm trying to raspberry pi with patchbox os. Installation was easy and hassle-free. 
I have Loop192 running with gui and I send OSC commands from mididing to it, where they are created from the midi signal from the FCB 1010 pedal.
First "/loop/#/hit record " work propertly, In gui is "RECORD" blinking before recording and the recording is started correctly.
Second "/loop/#/hit record " dont stop recording at next cycle beginning. "RECORD" blinking and at start on next cycle again starting recording, 
Clicking by mouse working propertly.

**Comment by jean-emmanuel** [comment]
Could you check the exact sequence of osc messages sent by mididings ? A quick try here with pyliblo-utils' `send_osc` command rom the terminal did not make the bug happen.

**Comment by ToFFmashines** [comment]
Hallo,

I try this simply python script
`import liblo, sys

try:
    target = liblo.Address(3819)
except liblo.AddressError, err:
    print str(err)
    sys.exit()

liblo.send(target, "/loop/0/hit", "record")
`
In this case all working correctly. Please accept my apology. And close this issue.
Problem will be on side of mididings. Although I have no idea where the problem is, I use the same wording as in the script. I will investigate further.
Thank you for the quick response and work on loop192.
Tomas

**Comment by jean-emmanuel** [comment]
You could run `dump_osc 3819` in a terminal (without loop192 running) and check what mididings sends when you hit the FCB, maybe there's a extra message that makes loop192 fail at some point.
You're welcome, I'm glad it can be of use.

**Comment by ToFFmashines** [comment]
Thanks for advice. I found an error in my script. I forgot to delete the line in which I repeatedly sent /play to loop192. 
Now its working fine.
I apologize again. Your code, by contrast, is mine without error :-)
